Factor out munge-enable, compd-enable, dispatchd-enable munge-enable: Add code for installing key file

diff --git a/Sys-scripts/munge-enable b/Sys-scripts/munge-enable
--- a/Sys-scripts/munge-enable
+++ b/Sys-scripts/munge-enable
@@ -2,6 +2,19 @@
 
 ##########################################################################
 #   Function description:
+#       Pause until user presses return
+##########################################################################
+
+pause()
+{
+    local junk
+    
+    printf "Press return to continue..."
+    read junk
+}
+
+##########################################################################
+#   Function description:
 #       Enable munge daemon
 #       
 #   History:
@@ -12,9 +25,86 @@
 munge_key=$(auto-localbase)/etc/munge/munge.key
 if [ -e $munge_key ]; then
     printf "$munge_key already exists.  Update it if necessary.\n"
+    pause
 else
-    printf "Copy munge.key from $head_node to $munge_key.\n"
+    valid=no
+    while [ $valid != yes ]; do
+	cat << EOM
+
+The munge authentication service requires a key in $munge_key,
+which must be identical on computers in this cluster/grid.  The file
+is not present on this computer.  Please choose from the following options
+to install the key file:
+
+1.. Generate new munge key for this cluster/grid
+2.. Automatically and securely scp munge key from another system
+3.. Pause this script and manually install munge key from elsewhere
+
+EOM
+	printf "Selection? "
+	read selection
+	
+	case 0"$selection" in
+	01)
+	    if mungekey; then
+		valid=yes
+	    fi
+	    ;;
+	
+	02)
+	    valid=yes
+	    printf "Hostname of computer with munge key? "
+	    read host_name
+	    cat << EOM
+
+Enter the username of a user that exists on both $host_name
+and $(hostname), and has permission to "su" to root.
+On BSD and some Linux systems, this user must be a member of the
+root or wheel group.
+
+This user cannot be "root".  Secure systems do not accept remote logins
+as the root user.
+
+You will need to enter the root password for $host_name
+and the user's password for $(hostname).
+
+EOM
+	    printf "Username? "
+	    read user_name
+	    set +e
+	    ssh -t $user_name@$host_name asroot \
+		scp -p $munge_key $user_name@$(hostname):
+	    if [ $(uname) = Darwin ]; then
+		mv ~$user_name/munge.key $munge_key
+	    else
+		user_home=$(awk -F : -v u=$user_name '$1 == u { print $6 }' /etc/passwd)
+		mv $user_home/munge.key $munge_key
+	    fi
+	    set -e
+	    if chown root:0 $munge_key && chmod 600 $munge_key; then
+		valid=yes
+	    fi
+	    ;;
+	
+	03)
+	    printf "Securely copy your key file to $munge_key.\n"
+	    printf "Ensure that it it not readable to ordinary users at any time.\n"
+	    pause
+	    valid=yes
+	    if chown root:0 $munge_key && chmod 600 $munge_key; then
+		valid=yes
+	    fi
+	    ;;
+	
+	*)
+	    printf "Invalid selection.\n" >> /dev/stderr
+	    ;;
+	
+	esac
+	pause
+    done
 fi
+
 printf "Permissions should be -rw-------\n"
 printf "and ownership root:root or root:wheel or daemon:daemon.\n"
 printf "If they are not, you may have a security breach.\n"
